/* Mushaf data generated by scripts/build-mushaf.py from the KFGQPC Hafs files. */

export type HeaderLine = { h: number };
export type BasmalahLine = { b: string };
/** t: words separated by spaces, v: runs of [verseIndex, wordCount], w: natural width in em, c: centered */
export type TextLine = { t: string; v: [number, number][]; w: number; c?: 1 };
export type Line = HeaderLine | BasmalahLine | TextLine;

export type Surah = {
  n: number;
  name: string;
  en: string;
  type: string;
  ayahs: number;
  page: number;
};

export type Juz = { juz: number; page: number; s: number; a: number };

type Meta = {
  pageCount: number;
  maxLineEm: number;
  refLineEm: number;
  surahs: Surah[];
  juz: Juz[];
  /** verse index -> [surah, ayah, page where the verse ends, juz] */
  verses: [number, number, number, number][];
};

const meta: Meta = require("../assets/mushaf/meta.json");
export const pages: Line[][] = require("../assets/mushaf/pages.json");

export const PAGE_COUNT = meta.pageCount;
export const REF_LINE_EM = meta.refLineEm;
export const surahs = meta.surahs;
export const juzList = meta.juz;

export const isHeader = (l: Line): l is HeaderLine => "h" in l;
export const isBasmalah = (l: Line): l is BasmalahLine => "b" in l;
export const isText = (l: Line): l is TextLine => "t" in l;

/** page: the page where the verse starts (a verse can run over to the next page). */
export type VerseRef = { index: number; surah: number; ayah: number; page: number; juz: number };

export function verse(index: number): VerseRef {
  const [surah, ayah, , juz] = meta.verses[index];
  return { index, surah, ayah, page: verseStartPage[index], juz };
}

export function verseIndex(surah: number, ayah: number): number {
  const first = firstVerseOfSurah[surah - 1];
  return first + ayah - 1;
}

const firstVerseOfSurah: number[] = [];
meta.verses.forEach(([s, a], i) => {
  if (a === 1) firstVerseOfSurah[s - 1] = i;
});

export type PageInfo = {
  page: number;
  firstVerse: number;
  lastVerse: number;
  surahs: number[];
  juz: number;
};

const verseStartPage: number[] = [];
const surahHeader: { page: number; atTop: boolean }[] = [];

export const pageInfo: PageInfo[] = pages.map((lines, i) => {
  let first = -1;
  let last = -1;
  const surahSet: number[] = [];
  lines.forEach((line, li) => {
    if (isHeader(line)) {
      surahHeader[line.h - 1] = { page: i + 1, atTop: li === 0 };
      if (!surahSet.includes(line.h)) surahSet.push(line.h);
    }
    if (!isText(line)) return;
    for (const [v] of line.v) {
      if (first < 0) first = v;
      last = v;
      if (verseStartPage[v] === undefined) verseStartPage[v] = i + 1;
      const s = meta.verses[v][0];
      if (!surahSet.includes(s)) surahSet.push(s);
    }
  });
  surahSet.sort((a, b) => a - b);
  return { page: i + 1, firstVerse: first, lastVerse: last, surahs: surahSet, juz: meta.verses[first][3] };
});

for (const s of surahs) s.page = surahHeader[s.n - 1].page;

/** First and last page of a surah. */
export function surahPages(n: number): [number, number] {
  const start = surahHeader[n - 1].page;
  if (n === surahs.length) return [start, PAGE_COUNT];
  const next = surahHeader[n];
  return [start, Math.max(start, next.atTop ? next.page - 1 : next.page)];
}

export type PageWord = {
  /** Position of the word on the page, in reading order. */
  index: number;
  text: string;
  verse: number;
  /** End-of-verse mark (the font draws the ayah number inside it). */
  isMark: boolean;
  firstOfVerse: boolean;
};

export type PageLine =
  | { kind: "header"; surah: number }
  | { kind: "basmalah"; text: string }
  | { kind: "text"; words: PageWord[]; widthEm: number; centered: boolean };

const pageLinesCache = new Map<number, { lines: PageLine[]; words: PageWord[] }>();

export function pageLayout(page: number): { lines: PageLine[]; words: PageWord[] } {
  const cached = pageLinesCache.get(page);
  if (cached) return cached;
  const words: PageWord[] = [];
  const lines: PageLine[] = pages[page - 1].map((line): PageLine => {
    if (isHeader(line)) return { kind: "header", surah: line.h };
    if (isBasmalah(line)) return { kind: "basmalah", text: line.b };
    const texts = line.t.split(" ");
    const lineWords: PageWord[] = [];
    let k = 0;
    for (const [v, count] of line.v) {
      for (let i = 0; i < count; i++, k++) {
        const prev = words[words.length - 1];
        const word: PageWord = {
          index: words.length,
          text: texts[k],
          verse: v,
          isMark: false,
          firstOfVerse: false,
        };
        const code = word.text.charCodeAt(0);
        word.isMark = word.text.length === 1 && code >= 0xfc00 && code <= 0xfdff;
        const continuesFromPreviousPage = !prev && page > 1 && pageInfo[page - 2].lastVerse === v;
        word.firstOfVerse = !word.isMark && (prev ? prev.verse !== v : !continuesFromPreviousPage);
        words.push(word);
        lineWords.push(word);
      }
    }
    return { kind: "text", words: lineWords, widthEm: line.w, centered: line.c === 1 };
  });
  const result = { lines, words };
  pageLinesCache.set(page, result);
  return result;
}

let verseTexts: string[] | null = null;
/** Verse text without the end-of-verse mark. Loaded on first use. */
export function verseText(index: number): string {
  if (!verseTexts) verseTexts = require("../assets/mushaf/text.json");
  return verseTexts![index];
}

let searchTexts: string[] | null = null;
export function searchCorpus(): string[] {
  if (!searchTexts) searchTexts = require("../assets/mushaf/search.json");
  return searchTexts!;
}
